In [1]:
pip install tensorflow


In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.19.0


Create Tensors

In [4]:
a= tf.constant(5)
print(a)

v=tf.constant([1,2,3,4])
print(v)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [5]:
m=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(m)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [6]:

s = tf.constant([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(s)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]], shape=(2, 3, 3), dtype=int32)


In [7]:
a = tf.constant([20,24,27,32,40])
b = tf.constant([1,2,3,4,5])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tf.Tensor([21 26 30 36 45], shape=(5,), dtype=int32)
tf.Tensor([19 22 24 28 35], shape=(5,), dtype=int32)
tf.Tensor([ 20  48  81 128 200], shape=(5,), dtype=int32)
tf.Tensor([20. 12.  9.  8.  8.], shape=(5,), dtype=float64)


In [8]:
a = tf.constant([1,2,3,4,5])
print(a.dtype,a.shape,tf.rank(a))

<dtype: 'int32'> (5,) tf.Tensor(1, shape=(), dtype=int32)


In [9]:
import numpy as np
np_array = ([[1,2,3],[4,5,6]])

tensor = tf.convert_to_tensor(np_array)
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
